#include "../../config.h"

#define GRAVE_ESC_ALT_OVERRIDE
//#define LSPO_KEY KC_ENT
//#define AUTO_SHIFT_TIMEOUT 150
#define NO_AUTO_SHIFT_NUMERIC
#define NO_AUTO_SHIFT_ALPHA
#define TAPPING_TERM 200
#define TAPPING_FORCE_HOLD